resilience4j:
  ratelimiter:
    instances:

      # RateLimiter object used in RateLimitingService.basicExample()
      basicExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s

      # RateLimiter object used in RateLimitingService.timeoutExample()
      timeoutExample:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms

      # RateLimiter object used in RateLimitingService.multipleRateLimitsExample()
      multipleRateLimiters_rps_limiter:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 2s

      multipleRateLimiters_rpm_limiter:
        limitForPeriod: 40
        limitRefreshPeriod: 1m
        timeoutDuration: 2s


      # RateLimiter object used in RateLimitingService.rateLimiterEventsExample()
      rateLimiterEventsExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 50ms
